<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
</head>
<body>

<H2 style="text-align: center">THIS IS NOT AN ID, PLEASE UPLOAD AN ID</H2>
<p>
    <a href="/signUp">
        <button>REGISTER</button>
    </a>
</p>
</body>
</html>